name: Custom Bug Report
description: Something went wrong? Let us know!
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Before submitting a bug report, please read the following instructions:**

        - Make sure the issue hasn't already been addressed by searching through existing and past issues.
        - Use a clear and concise title for your bug report.
        - Fill out all relevant sections below to help us understand and reproduce the issue.
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. <your_email>@gmail.com
    validations:
      required: True

  - type: checkboxes
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - label: "*feat*: add / modified function."
        - label: "*fix*: bug fix"
        - label: "*docs*: documentation"
        - label: "*style*: code style for white-space, formatting, missing semi colons, etc"
        - label: "*refactor*: restructuring code, while not changing its original functionality"
        - label: "*perf*: A code change that improves performance"
        - label: "*test*: when adding missing tests"
    validations:
      required: True
  
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the bug.
    validations:
      required: True

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: Describe what you expected to happen.
    validations:
      required: True
  
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: |
        If relevant, add a minimal example or detailed steps to reproduce the error. Provide detailed steps to reproduce the behavior.

      placeholder: "```python\n# your code\n```"
    validations:
      required: False

  - type: textarea
    id: versions
    attributes:
      label: Environment Details
      description: Provide information about your version, setup, and any other relevant environment details.
    validations:
      required: False

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Copy and paste any relevant log output here.
      render: shell
    validations:
      required: False
      
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running?
      # multiple: true
      options:
        - platform_#1 (Default)
        - platform_#2
      default: 0
    validations:
      required: True
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: True